"""Centralized Hager framework imports.

The OpenAI Agents SDK uses the package name `agents`, which collides with
Hager's `agents/` directory (containing AgentAction.py, prompts.py, etc.).

Strategy: temporarily swap out the SDK's `agents` module from sys.modules,
create a temporary __init__.py in Hager's agents/ to make it a proper package,
import what we need, then restore the SDK module.

All Hager-framework imports should go through this module.
"""

import os
import sys
import importlib
import importlib.util

_HAGER_ROOT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "codes_Hager",
    "MIMIC-Clinical-Decision-Making-Framework",
)

# Hager's agents/ directory lacks __init__.py, which means Python won't
# recognize it as a package when the SDK's `agents` is installed.
# Create it if missing.
_HAGER_AGENTS_INIT = os.path.join(_HAGER_ROOT, "agents", "__init__.py")
if not os.path.exists(_HAGER_AGENTS_INIT):
    with open(_HAGER_AGENTS_INIT, "w") as f:
        f.write("# Auto-generated by codes_openai_agent/hager_imports.py\n")


def _save_sdk_agents():
    """Save and remove the SDK's `agents` module and submodules from sys.modules."""
    saved = {}
    for key in list(sys.modules.keys()):
        if key == "agents" or key.startswith("agents."):
            saved[key] = sys.modules.pop(key)
    return saved


def _restore_sdk_agents(saved):
    """Remove any Hager `agents` entries and restore SDK's agents module."""
    for key in list(sys.modules.keys()):
        if key == "agents" or key.startswith("agents."):
            if key not in saved:
                sys.modules.pop(key, None)
    sys.modules.update(saved)


def _import_from_hager(dotted_name: str):
    """Import a module from Hager's framework, handling the agents collision."""
    saved = _save_sdk_agents()
    sys.path.insert(0, _HAGER_ROOT)
    try:
        if dotted_name in sys.modules:
            del sys.modules[dotted_name]
        mod = importlib.import_module(dotted_name)
        return mod
    finally:
        if _HAGER_ROOT in sys.path:
            sys.path.remove(_HAGER_ROOT)
        _restore_sdk_agents(saved)


def _import_file_directly(module_name: str, file_path: str):
    """Import a single Python file by path, registering it in sys.modules."""
    spec = importlib.util.spec_from_file_location(module_name, file_path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = mod  # Must register BEFORE exec for @dataclass
    spec.loader.exec_module(mod)
    return mod


# --- AgentAction (simple file, no transitive deps) ---
_agent_action_mod = _import_file_directly(
    "hager_AgentAction",
    os.path.join(_HAGER_ROOT, "agents", "AgentAction.py"),
)
AgentAction = _agent_action_mod.AgentAction


# --- dataset/utils.py (simple file, no transitive deps on agents/) ---
_dataset_utils_mod = _import_file_directly(
    "hager_dataset_utils",
    os.path.join(_HAGER_ROOT, "dataset", "utils.py"),
)


def load_hadm_from_file(filename, base_mimic=""):
    """Load patient data from pickle file."""
    return _dataset_utils_mod.load_hadm_from_file(filename, base_mimic=base_mimic)


# --- Lazy-loaded modules with transitive deps ---
_actions_mod = None
_nlp_mod = None
_evaluator_classes = None


def get_actions():
    """Get Hager's tools.Actions module (lazy-loaded)."""
    global _actions_mod
    if _actions_mod is None:
        _actions_mod = _import_from_hager("tools.Actions")
    return _actions_mod


def get_nlp():
    """Get Hager's utils.nlp module (lazy-loaded)."""
    global _nlp_mod
    if _nlp_mod is None:
        _nlp_mod = _import_from_hager("utils.nlp")
    return _nlp_mod


def get_evaluator_classes():
    """Load all 4 PathologyEvaluator subclasses (lazy-loaded)."""
    global _evaluator_classes
    if _evaluator_classes is not None:
        return _evaluator_classes

    saved = _save_sdk_agents()

    # Temporarily remove codes_openai_agent/ from sys.path so our tools.py
    # doesn't shadow Hager's tools/ package (evaluators import tools.utils).
    _our_root = os.path.dirname(os.path.abspath(__file__))
    _removed_paths = []
    for p in [_our_root]:
        if p in sys.path:
            sys.path.remove(p)
            _removed_paths.append(p)

    # Also swap out our `tools` module from sys.modules — it's cached as
    # codes_openai_agent/tools.py (a file), which blocks `tools.utils`.
    _saved_tools = {}
    for key in list(sys.modules.keys()):
        if key == "tools" or key.startswith("tools."):
            _saved_tools[key] = sys.modules.pop(key)

    sys.path.insert(0, _HAGER_ROOT)
    try:
        from evaluators.appendicitis_evaluator import AppendicitisEvaluator
        from evaluators.cholecystitis_evaluator import CholecystitisEvaluator
        from evaluators.diverticulitis_evaluator import DiverticulitisEvaluator
        from evaluators.pancreatitis_evaluator import PancreatitisEvaluator

        _evaluator_classes = {
            "appendicitis": AppendicitisEvaluator,
            "cholecystitis": CholecystitisEvaluator,
            "diverticulitis": DiverticulitisEvaluator,
            "pancreatitis": PancreatitisEvaluator,
        }
        return _evaluator_classes
    finally:
        if _HAGER_ROOT in sys.path:
            sys.path.remove(_HAGER_ROOT)
        for p in _removed_paths:
            if p not in sys.path:
                sys.path.insert(0, p)
        # Restore our tools module (remove Hager's tools entries first)
        for key in list(sys.modules.keys()):
            if key == "tools" or key.startswith("tools."):
                if key not in _saved_tools:
                    sys.modules.pop(key, None)
        sys.modules.update(_saved_tools)
        _restore_sdk_agents(saved)


def load_evaluator(pathology: str):
    """Create a fresh PathologyEvaluator instance for the given pathology."""
    classes = get_evaluator_classes()
    cls = classes.get(pathology)
    if cls is None:
        raise ValueError(
            f"Unknown pathology: {pathology}. "
            f"Choose from {list(classes.keys())}"
        )
    return cls()
