# @package _global_
defaults:
  - _self_

anthropic_api_key: ${oc.env:ANTHROPIC_API_KEY,""}

model_name: claude-opus-4-6
max_context_length: 200000
exllama: False

system_tag_start: "<|im_start|>system"
system_tag_end: "<|im_end|>"

user_tag_start: "<|im_start|>user"
user_tag_end: "<|im_end|>"

ai_tag_start: "<|im_start|>assistant"
ai_tag_end: "<|im_end|>"

stop_words: []
