# @package _global_
defaults:
  - _self_

openai_api_key: ${oc.env:OPENAI_API_KEY,""}

model_name: gpt-5-mini
max_context_length: 400000
reasoning_effort: medium
exllama: False

system_tag_start: "<|im_start|>system"
system_tag_end: "<|im_end|>"

user_tag_start: "<|im_start|>user"
user_tag_end: "<|im_end|>"

ai_tag_start: "<|im_start|>assistant"
ai_tag_end: "<|im_end|>"

stop_words: []
